services:
  mongo:
    image: mongo:8
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: label-generator
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
