services:
  mongo:
    image: mongo:8
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: label-generator
    volumes:
      - mongodata:/data/db

  compass:
    image: haohanyang/compass-web
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      CW_MONGO_URI: "mongodb://root:example@mongo:27017/label-generator?authSource=admin"
    depends_on:
      - mongo

volumes:
  mongodata:
